### ISSUE TITLE
Occasional error during process loading

### ISSUE THREAD

**Issue by ylep** [brainvisa/axon#18]
This error appears randomly (about 1 in 500 times) while running many BrainVISA processes in parallel in soma-workflow:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/volatile/bv/build/bug_fix/python/brainvisa/axon/runprocess.py", line 371, in <module>
    axon.initializeProcesses()
  File "/volatile/bv/build/bug_fix/python/brainvisa/axon/processes.py", line 160, in initializeProcesses
    brainvisa.processes.readProcesses(neuroConfig.processesPath)
  File "/volatile/bv/build/bug_fix/python/brainvisa/processes.py", line 6214, in readProcesses
    'Cannot read processes cache file <em>%s</em>') % (processesCacheFile, )),
  File "/volatile/bv/build/bug_fix/python/brainvisa/processing/neuroException.py", line 91, in exceptionHTML
    msg = exceptionMessageHTML( exceptionInfo, beforeError=beforeError, afterError=afterError ) + '<hr>' + \
  File "/volatile/bv/build/bug_fix/python/brainvisa/processing/neuroException.py", line 109, in exceptionMessageHTML
    txt = "<b>" + htmlEscape(unicode(v)) + "</b>"
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 2: invalid start byte
```

**Comment by ylep** [comment]
I think there are actually two issues here: 

1. a race condition that occurs when the process cache file is being read by a process, and simultaneously written to by another process

2. an encoding error that happens when calling unicode() on the exception that occurs during reading of the process cache file
