### ISSUE TITLE
Error about axon-runprocess command

### ISSUE THREAD

**Issue by rbregand** [brainvisa/axon#53]
Hi, 

I just hear about the axon-runprocess way to use SPM. I typed this following line into casa distro bash **axon-runprocess --list-processes** but theses errors  appear 

```
Traceback (most recent call last):
  File "/casa/host/build/python/brainvisa/processes.py", line 4712, in getProcessInstance
    if (isinstance(processIdClassOrInstance, six.string_types) or hasattr(processIdClassOrInstance, 'readline')) and minfFormat(processIdClassOrInstance)[1] == minfHistory:
  File "/casa/host/build/python/soma/minf/api.py", line 118, in minfFormat
    opened_source_file = open(source, encoding='UTF-8')
FileNotFoundError: [Errno 2] No such file or directory: 'spm8_table_measures'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/casa/host/build/bin/axon-runprocess", line 4, in <module>
    run_module('brainvisa.axon.runprocess')
  File "/usr/lib/python3.6/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/casa/host/build/python/brainvisa/axon/runprocess.py", line 383, in <module>
    hide=options.hide_proc_attrib)
  File "/casa/host/build/python/brainvisa/axon/processinfo.py", line 192, in process_list_help
    processes.readProcdoc(pi.id)  # ensure doc is here
  File "/casa/host/build/python/brainvisa/processes.py", line 307, in readProcdoc
    proc = getProcessInstance(processId)
  File "/casa/host/build/python/brainvisa/processes.py", line 4721, in getProcessInstance
    result = result()
  File "/casa/host/build/python/brainvisa/processes.py", line 1499, in __init__
    Parameterized.__init__(self, self.signature.shallowCopy())
  File "/casa/host/build/python/brainvisa/processes.py", line 809, in __init__
    self.initialization()
  File "/casa/host/build/brainvisa/toolboxes/catidb/processes/create_table_measures.py", line 28, in initialization
    ProcessExecutionNode('spm8_table_measures', optional=1))
  File "/casa/host/build/python/brainvisa/processes.py", line 2563, in __init__
    process = getProcessInstance(process)
  File "/casa/host/build/python/brainvisa/processes.py", line 4719, in getProcessInstance
    + '": invalid identifier or process file: ' + repr(e))
KeyError: 'Could not get process "\'spm8_table_measures\'": invalid identifier or process file: FileNotFoundError(2, \'No such file or directory\')'
```
I tried to rebuild from scratch a new casa distro but the previous errors still occurs.

Howewer, the threshold commands from the online documentation seem to work nicely (https://brainvisa.info/axon/user_doc/axon_manual2.html#brainvisa-commandline).

Anyone else facing the same issue ? 
Any ideas to resolve it ? 

Image_version :  5.0.3
os : Linux Mint 20.1

Thanks for your help,
Rémy

**Comment by denisri** [comment]
I have pushed an attempt to fix it:: 8efd9b87c43c7c706611e79ca0ee6e8d64cccb9c / b0404184290048e64cc89c302ab459da0ede73f7
Please tell us if it changes anything for you...

**Comment by rbregand** [comment]
The correction is working, I can now see the processes list. 
However some errors occurs. It seems 2 modules are missing pydicom and Anatomist (multiple errors). You will find bellow the log (I just paste an extract of Anatomist issues, they are all sames : module 'anatomist.threaded' has no attribute 'Anatomist'
 ):
```
ModuleNotFoundError: /casa/host/build/brainvisa/toolboxes/catidb/processes/pet_processes/push_pet_bids_json.py: No module named 'pydicom'

**

* * *

`**ModuleNotFoundError**`

    
    
    Traceback (most recent call last):
      File "/casa/host/build/python/brainvisa/processes.py", line 5933, in readProcess
        moduleName, fileIn, fileName, moduleDescription)
      File "/usr/lib/python3.6/imp.py", line 235, in load_module
        return load_source(name, filename, file)
      File "/usr/lib/python3.6/imp.py", line 172, in load_source
        module = _load(spec)
      File "<frozen importlib._bootstrap>", line 684, in _load
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/casa/host/build/brainvisa/toolboxes/catidb/processes/pet_processes/push_pet_bids_json.py", line 42, in <module>
        from nuclearImaging.bids_json_mn import generate_pet_json
      File "/casa/host/build/python/nuclearImaging/bids_json_mn.py", line 5, in <module>
        import pydicom
    ModuleNotFoundError: No module named 'pydicom'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/casa/host/build/python/brainvisa/processes.py", line 6363, in addDir
        toolbox=toolbox)  # two arguments : process fullpath and category (directories separated by /)
      File "/casa/host/build/python/brainvisa/processes.py", line 5948, in readProcess
        sys.exc_info()[2])
      File "/usr/local/lib/python3.6/dist-packages/six.py", line 718, in reraise
        raise value.with_traceback(tb)
      File "/casa/host/build/python/brainvisa/processes.py", line 5933, in readProcess
        moduleName, fileIn, fileName, moduleDescription)
      File "/usr/lib/python3.6/imp.py", line 235, in load_module
        return load_source(name, filename, file)
      File "/usr/lib/python3.6/imp.py", line 172, in load_source
        module = _load(spec)
      File "<frozen importlib._bootstrap>", line 684, in _load
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/casa/host/build/brainvisa/toolboxes/catidb/processes/pet_processes/push_pet_bids_json.py", line 42, in <module>
        from nuclearImaging.bids_json_mn import generate_pet_json
      File "/casa/host/build/python/nuclearImaging/bids_json_mn.py", line 5, in <module>
        import pydicom
    ModuleNotFoundError: /casa/host/build/brainvisa/toolboxes/catidb/processes/pet_processes/push_pet_bids_json.py: No module named 'pydicom'
    

QApplication already instantiated, headless Anatomist is not possible.


ERROR: **

    
    
    AttributeError: /casa/host/build/brainvisa/toolboxes/cortical_surface/processes/viewers/AnatomistShowBasinsTexture.py: module 'anatomist.threaded' has no attribute 'Anatomist'

**

* * *

`**AttributeError**`

    
    
    Traceback (most recent call last):
      File "/casa/host/build/python/brainvisa/processes.py", line 5933, in readProcess
        moduleName, fileIn, fileName, moduleDescription)
      File "/usr/lib/python3.6/imp.py", line 235, in load_module
        return load_source(name, filename, file)
      File "/usr/lib/python3.6/imp.py", line 172, in load_source
        module = _load(spec)
      File "<frozen importlib._bootstrap>", line 684, in _load
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/casa/host/build/brainvisa/toolboxes/cortical_surface/processes/viewers/AnatomistShowBasinsTexture.py", line 35, in <module>
        from brainvisa import anatomist
      File "/casa/host/build/python/brainvisa/anatomist/__init__.py", line 107, in <module>
        class Anatomist(anatomistModule.Anatomist):
    AttributeError: module 'anatomist.threaded' has no attribute 'Anatomist'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/casa/host/build/python/brainvisa/processes.py", line 6363, in addDir
        toolbox=toolbox)  # two arguments : process fullpath and category (directories separated by /)
      File "/casa/host/build/python/brainvisa/processes.py", line 5948, in readProcess
        sys.exc_info()[2])
      File "/usr/local/lib/python3.6/dist-packages/six.py", line 718, in reraise
        raise value.with_traceback(tb)
      File "/casa/host/build/python/brainvisa/processes.py", line 5933, in readProcess
        moduleName, fileIn, fileName, moduleDescription)
      File "/usr/lib/python3.6/imp.py", line 235, in load_module
        return load_source(name, filename, file)
      File "/usr/lib/python3.6/imp.py", line 172, in load_source
        module = _load(spec)
      File "<frozen importlib._bootstrap>", line 684, in _load
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/casa/host/build/brainvisa/toolboxes/cortical_surface/processes/viewers/AnatomistShowBasinsTexture.py", line 35, in <module>
        from brainvisa import anatomist
      File "/casa/host/build/python/brainvisa/anatomist/__init__.py", line 107, in <module>
        class Anatomist(anatomistModule.Anatomist):
    AttributeError: /casa/host/build/brainvisa/toolboxes/cortical_surface/processes/viewers/AnatomistShowBasinsTexture.py: module 'anatomist.threaded' has no attribute 'Anatomist'
    

QApplication already instantiated, headless Anatomist is not possible.

```
Also thanks for the quick answer.

**Comment by denisri** [comment]
The error message with anatomist is strange. Do you also have it when running the "regular" `brainvisa` commandline ?
Anyway it's not the role of this script to print such messages, so I have suppressed all stdout/stderr during initialization in the `axon-runprocess` script.

**Comment by rbregand** [comment]
When I'm using brainvisa command line such as **brainvisa -r threshold** I have the error message about Anatomist
