### ISSUE TITLE
Crash upon exiting BrainVISA (ImportErrors and free(): invalid pointer)

### ISSUE THREAD

**Issue by ylep** [brainvisa/axon#65]
**Describe the bug**

Exiting BrainVISA makes it crash with the following messages (the `ImportError`s and `free(): invalid pointer` may or may not be related):

```
Exception ignored in: <function ThreadSafeSQLiteConnection.__del__ at 0x7f47f60b0790>
Traceback (most recent call last):
  File "/casa/host/build/python/soma/sqlite_tools.py", line 90, in __del__
  File "/casa/host/build/python/soma/sqlite_tools.py", line 159, in close
  File "/casa/host/build/python/soma/sqlite_tools.py", line 175, in close_connections
  File "/casa/host/build/python/soma/sqlite_tools.py", line 144, in delete_connection
  File "/usr/lib/python3.10/threading.py", line 1234, in getName
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ThreadSafeSQLiteConnection.__del__ at 0x7f47f60b0790>
Traceback (most recent call last):
  File "/casa/host/build/python/soma/sqlite_tools.py", line 90, in __del__
  File "/casa/host/build/python/soma/sqlite_tools.py", line 159, in close
  File "/casa/host/build/python/soma/sqlite_tools.py", line 175, in close_connections
  File "/casa/host/build/python/soma/sqlite_tools.py", line 144, in delete_connection
  File "/usr/lib/python3.10/threading.py", line 1234, in getName
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ThreadSafeSQLiteConnection.__del__ at 0x7f47f60b0790>
Traceback (most recent call last):
  File "/casa/host/build/python/soma/sqlite_tools.py", line 90, in __del__
  File "/casa/host/build/python/soma/sqlite_tools.py", line 159, in close
  File "/casa/host/build/python/soma/sqlite_tools.py", line 175, in close_connections
  File "/casa/host/build/python/soma/sqlite_tools.py", line 144, in delete_connection
  File "/usr/lib/python3.10/threading.py", line 1234, in getName
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ThreadSafeSQLiteConnection.__del__ at 0x7f47f60b0790>
Traceback (most recent call last):
  File "/casa/host/build/python/soma/sqlite_tools.py", line 90, in __del__
  File "/casa/host/build/python/soma/sqlite_tools.py", line 159, in close
  File "/casa/host/build/python/soma/sqlite_tools.py", line 175, in close_connections
  File "/casa/host/build/python/soma/sqlite_tools.py", line 144, in delete_connection
  File "/usr/lib/python3.10/threading.py", line 1234, in getName
ImportError: sys.meta_path is None, Python is likely shutting down
free(): invalid pointer
Aborted (core dumped)
```

**Environment:**
 - Engine: Singularity / VM
 - Version of BrainVISA: 5.1 branch
 - For local builds, version of the casa-dev image `casa-dev-5.3-14`

**Comment by denisri** [comment]
This happens in python 3.10 (casa-dev-5.3), and did not happen in python 3.6 (or not this way).

**Comment by denisri** [comment]
I could fix the sqlite messages, but not the free() error and abort signal.

**Comment by denisri** [comment]
The crash happens in exit handlers, in `pthread_kill()` and I have no clue on what can cause it.

**Comment by sapetnioc** [comment]
I just made a change to have a explicit deletion on database connection instead of errors with automatic deletion upon exit. It fixes the segfault at the exit for me. Please confirm and eventually close this issue.
