### ISSUE TITLE
Circular dependencies in included files for types

### ISSUE THREAD

**Issue by Hboni** [brainvisa/axon#8]
After a big update of all projects, I couldn't launch Brainvisa, I had a lot of errors like :

```Traceback (most recent call last):
  File "/home/hb255304/brainvisa/build/bug_fix/python/brainvisa/multipleExecfile.py", line 151, in execute
    execfile(file, self.globalDict, self.localDict)
  File "/home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/nuclearimaging/hierarchies/brainvisa-3.2.0/datscan_hierarchies.py", line 1, in <module>
    include('base')
  File "/home/hb255304/brainvisa/build/bug_fix/python/brainvisa/multipleExecfile.py", line 187, in _include
    self.execute(*args)
  File "/home/hb255304/brainvisa/build/bug_fix/python/brainvisa/multipleExecfile.py", line 178, in execute
    raise e
RuntimeError: while executing file /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/nuclearimaging/hierarchies/brainvisa-3.2.0/datscan_hierarchies.py (/home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/nuclearimaging/hierarchies/brainvisa-3.2.0/datscan_hierarchies.py) : while executing file base (/home/hb255304/brainvisa/build/bug_fix/brainvisa/hierarchies/brainvisa-3.2.0/base.py) : Circular dependencies in included files. Inclusion order: /home/hb255304/brainvisa/build/bug_fix/brainvisa/hierarchies/brainvisa-3.2.0/base.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/hierarchies/brainvisa-3.2.0/history.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/hierarchies/brainvisa-3.2.0/qualitycheck.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/hierarchies/brainvisa-3.2.0/raw_data.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/hierarchies/brainvisa-3.2.0/registration.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/cortical_surface/hierarchies/brainvisa-3.2.0/cortical_surface.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/longitudinal_pipelines/hierarchies/brainvisa-3.2.0/longitudinal.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/morphologist/hierarchies/brainvisa-3.2.0/anatomy.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/morphologist/hierarchies/brainvisa-3.2.0/morphologist_longitudinal.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/morphologist/hierarchies/brainvisa-3.2.0/sulci.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/nuclearimaging/hierarchies/brainvisa-3.2.0/OLDPetSubjectHierarchy.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/nuclearimaging/hierarchies/brainvisa-3.2.0/OLDPetSubjectHierarchy_Common.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/nuclearimaging/hierarchies/brainvisa-3.2.0/OLDPetSubjectHierarchy_PET.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/nuclearimaging/hierarchies/brainvisa-3.2.0/OLDPetSubjectHierarchy_T1.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/nuclearimaging/hierarchies/brainvisa-3.2.0/OLDnuclear_imaging.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/nuclearimaging/hierarchies/brainvisa-3.2.0/datscan_hierarchies.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/hierarchies/brainvisa-3.2.0/base.py
while executing file base (/home/hb255304/brainvisa/build/bug_fix/brainvisa/hierarchies/brainvisa-3.2.0/base.py) : Circular dependencies in included files. Inclusion order: /home/hb255304/brainvisa/build/bug_fix/brainvisa/hierarchies/brainvisa-3.2.0/base.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/hierarchies/brainvisa-3.2.0/history.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/hierarchies/brainvisa-3.2.0/qualitycheck.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/hierarchies/brainvisa-3.2.0/raw_data.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/hierarchies/brainvisa-3.2.0/registration.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/cortical_surface/hierarchies/brainvisa-3.2.0/cortical_surface.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/longitudinal_pipelines/hierarchies/brainvisa-3.2.0/longitudinal.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/morphologist/hierarchies/brainvisa-3.2.0/anatomy.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/morphologist/hierarchies/brainvisa-3.2.0/morphologist_longitudinal.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/morphologist/hierarchies/brainvisa-3.2.0/sulci.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/nuclearimaging/hierarchies/brainvisa-3.2.0/OLDPetSubjectHierarchy.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/nuclearimaging/hierarchies/brainvisa-3.2.0/OLDPetSubjectHierarchy_Common.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/nuclearimaging/hierarchies/brainvisa-3.2.0/OLDPetSubjectHierarchy_PET.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/nuclearimaging/hierarchies/brainvisa-3.2.0/OLDPetSubjectHierarchy_T1.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/nuclearimaging/hierarchies/brainvisa-3.2.0/OLDnuclear_imaging.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/nuclearimaging/hierarchies/brainvisa-3.2.0/datscan_hierarchies.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/toolboxes/nuclearimaging/hierarchies/brainvisa-3.2.0/nuclearImaging.py, /home/hb255304/brainvisa/build/bug_fix/brainvisa/hierarchies/brainvisa-3.2.0/base.py
```

I found that the issue came from 1930534, when I revert the file *aimsGlobals.py* before the commit, i didn't have errors anymore.

**Comment by denisri** [comment]
Have you checked all projects codes have actually been updated and are up-to-date ? (especially, do you have edited files in nuclear_imaging which could prevent an update ?)

**Comment by Hboni** [comment]
I used bv_maker sources to update all the projects, I additionally update only *nuclear_imaging* project and it is up-to-date, I checked all the modified files locally, and I don't have type/hierarchy files modify (or just with commentary). I tried with and without **formats** branch.

**Comment by denisri** [comment]
The included files in the "circular inclusion" error message are really strange: they list hierarchy files which are not related at all, which do not include each other. So I think the error message does not reflect what actually happend. Anyway I pushed a modif to display line numbers in the inclusion stack in the error message. I'm not sure it will really help, but we can try.

**Comment by denisri** [comment]
Is the error message you have posted the first one ?

**Comment by Hboni** [comment]
I founded the issue, `supported_io_formats` was not in my pyaims, so the very first line was that it didn't find `supported_io_formats`. I pull the aims-free project to have all the modifications. 
The thing that I don't really understand is that I made an entire bv_maker last week, but it didn't really update everything apparently.

**Comment by denisri** [comment]
OK I see. Well it's strange that the aims project has not been updated, if it happens again we'll have to check.
This shows 2 additional issues, then:
* I thought I made a test in aimsGlobals to handle the absence of `supported_io_formats`, so it clearly desn't work...
* the error messages for errors in hierarchy files are completely inappropriate. They really need a fix.

**Comment by denisri** [comment]
If it's OK now, then you can close the issue.

**Comment by Hboni** [comment]
Oh yeah, for the initial issue, it's fine, I close !
